# Generated by Django 5.2.5 on 2025-09-05 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rangraaz", "0002_customer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="role",
            field=models.ForeignKey(
                blank=True,
                default=1,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="rangraaz.role",
            ),
        ),
    ]
