# Generated by Django 5.2.5 on 2025-09-08 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rangraaz", "0004_category_subcategory"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Category",
        ),
        migrations.DeleteModel(
            name="SubCategory",
        ),
    ]
