# Generated by Django 6.0 on 2026-02-26 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rangraaz", "0006_alter_customer_name_alter_customer_phone_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="role",
            field=models.CharField(
                choices=[("admin", "Admin"), ("customer", "Customer")],
                default="customer",
                max_length=20,
            ),
        ),
        migrations.DeleteModel(
            name="Role",
        ),
    ]
