# Generated by Django 6.0 on 2026-03-02 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rangraaz", "0007_alter_customer_role_delete_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="google_id",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
