# Generated by Django 6.0 on 2026-09-02 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rangraaz", "0008_customer_email_customer_google_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="role",
            field=models.CharField(
                choices=[
                    ("superadmin", "Superadmin"),
                    ("admin", "Admin"),
                    ("customer", "Customer"),
                ],
                default="customer",
                max_length=20,
            ),
        ),
    ]
