# Generated by Django 5.2.5 on 2025-09-11 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rangraaz", "0005_delete_category_delete_subcategory"),
        ("sales", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="rangraaz.customer"
            ),
        ),
    ]
