# Generated by Django 5.2.5 on 2025-09-11 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0002_alter_order_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="products",
            field=models.JSONField(default=list),
        ),
    ]
