# Generated by Django 5.2.5 on 2025-09-18 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0003_order_products"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="shipping_address",
            field=models.JSONField(
                default=dict,
                help_text="Store shipping details as JSON object with keys: email, first_name, last_name, address, city, zipcode, state",
            ),
        ),
    ]
