# Generated by Django 6.0 on 2026-05-19 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rangraaz", "0008_customer_email_customer_google_id"),
        ("sales", "0004_alter_order_shipping_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="rangraaz.customer",
            ),
        ),
    ]
