# Generated by Django 6.0 on 2026-03-03 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="original_price",
            field=models.DecimalField(
                decimal_places=2, help_text="Price in USD", max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="products",
            name="sell_price",
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
    ]
