# Generated by Django 6.0 on 2026-03-05 11:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_alter_products_original_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="sku",
            field=models.CharField(
                max_length=100,
                unique=True,
                validators=[
                    django.core.validators.MinLengthValidator(
                        5, message="SKU must be at least 5 characters long."
                    )
                ],
            ),
        ),
    ]
