# Generated by Django 4.2.28 on 2026-05-15 16:49

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_sizestock'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('slug', models.SlugField(max_length=180, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20)),
                ('meta_description', models.TextField(blank=True, null=True)),
                ('show_in_header', models.BooleanField(default=False)),
                ('nav_label', models.CharField(blank=True, max_length=80, null=True)),
                ('nav_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nav_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nav_children', to='products.custompage')),
            ],
            options={
                'ordering': ['sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='PageBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(choices=[('slider', 'Slider'), ('campaign', 'Campaign'), ('products', 'Products')], max_length=30)),
                ('title', models.CharField(blank=True, max_length=180, null=True)),
                ('subtitle', models.TextField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(default=520)),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('video', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='video')),
                ('link', models.CharField(blank=True, max_length=500, null=True)),
                ('product_ids', models.JSONField(blank=True, default=list)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='products.custompage')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
