# Generated by Django 4.2.28 on 2026-05-17 04:19

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_custompage_pageblock'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('direct_url', models.CharField(blank=True, max_length=500, null=True)),
                ('hover_title', models.CharField(blank=True, max_length=120, null=True)),
                ('hover_subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('hover_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('button_style', models.CharField(choices=[('standard', 'Standard'), ('sale', 'Sale'), ('featured', 'Featured')], default='standard', max_length=20)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('show_dropdown', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'title'],
            },
        ),
        migrations.AddField(
            model_name='custompage',
            name='header_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pages', to='products.headergroup'),
        ),
    ]
