# Generated by Django 6.0 on 2026-09-02 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0008_subsubcategory_products_sub_subcategory_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sizestock",
            name="sku",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
