# Generated by Django 6.0 on 2026-09-02 07:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0009_sizestock_sku"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="sku",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.MinLengthValidator(
                        5, message="SKU must be at least 5 characters long."
                    )
                ],
            ),
        ),
    ]
