# Generated by Django 6.0 on 2026-09-02 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0011_alter_products_sku"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="products",
            name="size",
        ),
        migrations.RemoveField(
            model_name="products",
            name="sku",
        ),
    ]
